
-- Fix CO seeing exhibit-officer reports: avoid user_roles RLS by using security-definer has_role()
DROP POLICY IF EXISTS "Users can view case reports" ON public.reports;

CREATE POLICY "Users can view case reports" ON public.reports
FOR SELECT TO authenticated
USING (
  -- User created the report
  generated_by = auth.uid()
  OR
  -- User reviewed the report
  reviewed_by = auth.uid()
  OR
  -- User is assigned to or supervises the case (exclude CO from exhibit-officer reports)
  (
    EXISTS (
      SELECT 1
      FROM cases c
      WHERE c.id = reports.case_id
        AND (c.assigned_to = auth.uid() OR c.supervisor_id = auth.uid())
    )
    AND NOT (
      has_role(auth.uid(), 'commanding_officer'::app_role)
      AND public.has_role(reports.generated_by, 'exhibit_officer'::app_role)
    )
  )
  OR
  -- Administrator can see all
  has_role(auth.uid(), 'administrator'::app_role)
  OR
  -- Supervisor can see all
  has_role(auth.uid(), 'supervisor'::app_role)
  OR
  -- OCU can see all reports (including exhibit-officer reports)
  has_role(auth.uid(), 'officer_commanding_unit'::app_role)
  OR
  -- CO can see reports ONLY if NOT generated by exhibit officer
  (
    has_role(auth.uid(), 'commanding_officer'::app_role)
    AND NOT public.has_role(reports.generated_by, 'exhibit_officer'::app_role)
  )
);
